version: '3'

services:
  web:
    build: .
    volumes:
    - ./app/go/web/:/go/app/:rw
    networks:
      - basic

  lb:
    image: dockercloud/haproxy
    ports:
      - 8080:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basic

networks:
  basic:
    driver: bridge
